name: Playwright Tests
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
on:
  repository_dispatch:
    types: [test_result]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache auth
      id: cache-auth
      uses: actions/cache@v3
      with:
        path: |
          playwright/.auth/unsubscribed.json
          playwright/.auth/subscribed.json
        key: playwright-auth-${{ hashFiles('playwright/.auth/**') }}-${{ env.TIMESTAMP }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Send message on test failure
      if: ${{ failure() }}
      run: |
        # 获取 Workflow URL
        URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

        # 构建消息内容
        MESSAGE=$(cat <<EOF
        {
          "msg_type": "text",
          "content": {
            "text": "GitHub Actions Workflow URL: \n$URL"
          }
        }
        EOF
        )

        curl -X POST -H "Content-Type: application/json" \
        -d "$MESSAGE" \
        https://open.larksuite.com/open-apis/bot/v2/hook/298e3a34-c6ff-42da-81ad-67e400196e1b
